export enum ActionTypes {
  SET_TOKEN = "SET_TOKEN",
  REMOVE_TOKEN = "REMOVE_TOKEN",
  LOGIN = "LOGIN",
  SET_ORDERS = "SET_ORDERS",
  ADD_ORDERS = "ADD_ORDERS",
  DELETE_ORDER = "DELETE_ORDER",
  EDIT_ORDER = "EDIT_ORDER",
}
